// Generated by CoffeeScript 1.8.0
(function() {
  var Fizzbuzz;

  Fizzbuzz = (function() {
    function Fizzbuzz() {}

    Fizzbuzz.prototype.isDivisibleByThree = function(number) {
      return this._isDivisibleBy(3, number);
    };

    Fizzbuzz.prototype.isDivisibleByFive = function(number) {
      return this._isDivisibleBy(5, number);
    };

    Fizzbuzz.prototype.isDivisibleByFifteen = function(number) {
      return this._isDivisibleBy(15, number);
    };

    Fizzbuzz.prototype._isDivisibleBy = function(divisor, number) {
      return number % divisor === 0;
    };

    return Fizzbuzz;

  })();

  module.exports = Fizzbuzz;

}).call(this);
