// Generated by CoffeeScript 1.8.0
(function() {
  var Fizzbuzz;

  Fizzbuzz = (function() {
    function Fizzbuzz() {}

    Fizzbuzz.prototype.isDivisibleByThree = function(number) {
      return number % 3 === 0;
    };

    Fizzbuzz.prototype.isDivisibleByFive = function(number) {
      return number % 5 === 0;
    };

    Fizzbuzz.prototype.isDivisibleByFifteen = function(number) {
      return number % 15 === 0;
    };

    Fizzbuzz.prototype.isDivisibleBy = function(divisor, number) {
      return divisor % number === 0;
    };

    return Fizzbuzz;

  })();

  module.exports = Fizzbuzz;

}).call(this);
